import React from 'react';
import { ProteinProfile } from '../../types';
import { Download, FileText, CheckCircle2, ShieldCheck } from 'lucide-react';

interface ChecklistDownloaderProps {
  protein: ProteinProfile;
}

export const ChecklistDownloader: React.FC<ChecklistDownloaderProps> = ({ protein }) => {
  const generateChecklistMarkdown = () => {
    return `# Comprehensive Protein Analysis Protocol
Target Protein: ${protein.name} (${protein.geneSymbol})
UniProt Accession: ${protein.uniprotId} | PDB: ${protein.pdbId || 'AlphaFold'}
Organism: ${protein.organism}
Molecular Weight: ${protein.molecularWeight} | Theoretical pI: ${protein.isoelectricPoint}
Generated: ${new Date().toLocaleDateString()}
Platform: Master Bioinformatics with Arif (http://arif_bioinformatics_mastery.com)

---

## Phase 1: Sequence & Primary Characterization
- [ ] 1.1 Verify curated UniProtKB Swiss-Prot sequence: \`${protein.uniprotId}\`
- [ ] 1.2 Confirm theoretical Isoelectric Point (pI = ${protein.isoelectricPoint}) and Molecular Weight (${protein.molecularWeight})
- [ ] 1.3 Assess Grand Average of Hydropathicity (GRAVY) & Aliphatic Index
- [ ] 1.4 Predict Signal Peptide cleavage site (SignalP 6.0) & Transmembrane helices (TMHMM)

## Phase 2: Functional Domain & Motif Mapping
${protein.domains.map(d => `- [ ] 2.x Confirm domain: **${d.name}** (Residues ${d.start}-${d.end}) -> ${d.description}`).join('\n')}
- [ ] 2.3 Run InterProScan for catalytic active sites & metal-binding coordinates
- [ ] 2.4 Annotate predicted phosphorylation (NetPhos) and N-glycosylation sites

## Phase 3: 3D Structure Retrieval & Stereochemical Validation
- [ ] 3.1 Retrieve experimental PDB coordinates (${protein.pdbId || 'N/A'}) or AlphaFold DB model (\`${protein.alphaFoldId || 'AF-' + protein.uniprotId + '-F1'}\`)
- [ ] 3.2 Validate Ramachandran plot stereochemistry using PROCHECK (>90% in favored regions)
- [ ] 3.3 Verify AlphaFold per-residue pLDDT confidence scores across active site residues
- [ ] 3.4 Execute short 10-20 ns MD minimization in GROMACS / AMBER force field

## Phase 4: Binding Pocket Detection & Molecular Docking
- [ ] 4.1 Compute solvent-accessible cavities using CASTp 3.0 / PrankWeb
- [ ] 4.2 Define Cartesian grid box coordinates (center_x, center_y, center_z, size_x, size_y, size_z)
- [ ] 4.3 Prepare receptor (.pdbqt): Add polar hydrogens, assign Kollman charges
- [ ] 4.4 Perform virtual screening with AutoDock Vina / PyRx with exhaustiveness >= 16
- [ ] 4.5 Inspect 2D intermolecular interaction diagrams (H-bonds, Pi-stacking, salt bridges) in Discovery Studio

## Phase 5: Pathway Context & Biological Validation
- [ ] 5.1 Query STRING database for high-confidence Protein-Protein Interactions (PPI score > 0.700)
- [ ] 5.2 Analyze biological pathways:
${protein.pathways.map(p => `      * ${p}`).join('\n')}
- [ ] 5.3 Correlate target expression with public RNA-seq datasets (NCBI GEO / SRA)
- [ ] 5.4 Formulate wet-lab validation plan (RT-qPCR primers, recombinant expression, or CRISPR knockout)

---
*Generated by Arif Bioinformatics Research Hub • Official Website: http://arif_bioinformatics_mastery.com*
`;
  };

  const handleDownload = (format: 'md' | 'txt') => {
    const textContent = generateChecklistMarkdown();
    const mimeType = format === 'md' ? 'text/markdown;charset=utf-8;' : 'text/plain;charset=utf-8;';
    const blob = new Blob([textContent], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `${protein.geneSymbol.replace(/[^a-zA-Z0-9]/g, '_')}_analysis_checklist.${format}`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="p-4 rounded-3xl bg-white border border-orange-200 flex flex-col sm:flex-row sm:items-center justify-between gap-3 shadow-xs">
      <div className="flex items-center space-x-3">
        <div className="p-2.5 rounded-2xl bg-orange-100 text-orange-600 border border-orange-200">
          <FileText className="w-5 h-5" />
        </div>
        <div>
          <h4 className="text-xs font-extrabold text-slate-950">Safe Protein Analysis Checklist</h4>
          <p className="text-[11px] text-slate-600 font-medium">Download standardized protocol checklist for your research notes.</p>
        </div>
      </div>

      <div className="flex items-center space-x-2">
        <button
          onClick={() => handleDownload('md')}
          className="px-3 py-1.5 rounded-xl bg-orange-100 hover:bg-orange-200 text-orange-950 border border-orange-300 text-xs font-bold flex items-center space-x-1.5 transition-colors cursor-pointer shadow-xs"
        >
          <Download className="w-3.5 h-3.5" />
          <span>Download .MD</span>
        </button>
        <button
          onClick={() => handleDownload('txt')}
          className="px-3 py-1.5 rounded-xl bg-white hover:bg-orange-50 text-slate-800 border border-orange-200 text-xs font-bold flex items-center space-x-1.5 transition-colors cursor-pointer shadow-xs"
        >
          <Download className="w-3.5 h-3.5" />
          <span>Download .TXT</span>
        </button>
      </div>
    </div>
  );
};
